/*
 * kernel/src/dev/ata/atapi.h
 * © suhas pai
 */

#pragma once

enum atapi_command {
    ATAPI_COMMAND_TEST_UNIT_READY = 0x00,
    ATAPI_COMMAND_REQUEST_SENSE = 0x03,
    ATAPI_COMMAND_FORMAT_UNIT = 0x04,
    ATAPI_COMMAND_INQUIRY = 0x12,

    // (Eject device)
    ATAPI_COMMAND_START_STOP_UNIT = 0x1B,
    ATAPI_COMMAND_PREVENT_ALLOW_MEDIUM_REMOVAL = 0x1E,
    ATAPI_COMMAND_READ_FORMAT_CAPACITIES = 0x23,
    ATAPI_COMMAND_READ_CAPACITY = 0x25,
    ATAPI_COMMAND_READ_10 = 0x28,
    ATAPI_COMMAND_WRITE_10 = 0x2A,
    ATAPI_COMMAND_SEEK_10 = 0x2B,
    ATAPI_COMMAND_WRITE_AND_VERIFY_10 = 0x2E,
    ATAPI_COMMAND_VERIFY = 0x2F,
    ATAPI_COMMAND_SYNCHRONIZE_CACHE = 0x35,
    ATAPI_COMMAND_WRITE_BUFFER = 0x3B,
    ATAPI_COMMAND_READ_BUFFER = 0x3C,
    ATAPI_COMMAND_READ_TOC = 0x43,
    ATAPI_COMMAND_GET_CONFIGURATION	= 0x46,
    ATAPI_COMMAND_GET_EVENT_STATUS_NOTIFICATION = 0x4A,
    ATAPI_COMMAND_READ_DISC_INFORMATION = 0x51,
    ATAPI_COMMAND_READ_TRACK_INFORMATION = 0x52,
    ATAPI_COMMAND_RESERVE_TRACK = 0x53,
    ATAPI_COMMAND_SEND_OPC_INFORMATION = 0x54,
    ATAPI_COMMAND_MODE_SELECT = 0x55,
    ATAPI_COMMAND_REPAIR_TRACK = 0x58,
    ATAPI_COMMAND_MODE_SENSE = 0x5A,
    ATAPI_COMMAND_CLOSE_TRACK_SESSION = 0x5B,
    ATAPI_COMMAND_READ_BUFFER_CAPACITY = 0x5C,
    ATAPI_COMMAND_SEND_CUE_SHEET = 0x5D,
    ATAPI_COMMAND_REPORT_LUNS = 0xA0,
    ATAPI_COMMAND_BLANK = 0xA1,
    ATAPI_COMMAND_SECURITY_PROTOCOL_IN = 0xA2,
    ATAPI_COMMAND_SEND_KEY = 0xA3,
    ATAPI_COMMAND_REPORT_KEY = 0xA4,
    ATAPI_COMMAND_LOAD_UNLOAD_MEDIUM = 0xA6,
    ATAPI_COMMAND_SET_READ_AHEAD	= 0xA7,
    ATAPI_COMMAND_READ =	0xA8,
    ATAPI_COMMAND_WRITE = 0xAA,
    ATAPI_COMMAND_READ_MEDIA_SERIAL_NUMBER = 0xAB,
    ATAPI_COMMAND_GET_PERFORMANCE = 0xAC,
    ATAPI_COMMAND_READ_DISC_STRUCTURE = 0xAD,
    ATAPI_COMMAND_SECURITY_PROTOCOL_OUT = 0xB5,
    ATAPI_COMMAND_SET_STREAMING = 0xB6,
    ATAPI_COMMAND_READ_CD_MSF = 0xB9,
    ATAPI_COMMAND_SET_CD_SPEED = 0xBB,
    ATAPI_COMMAND_MECHANISM_STATUS = 0xBD,
    ATAPI_COMMAND_READ_CD = 0xBE,
    ATAPI_COMMAND_SEND_DISC_STRUCTURE = 0xBF,
};