/*
 * kernel/src/dev/ata/atapi.h
 * © suhas pai
 */

#pragma once

enum atapi_command {
    ATAPI_WRITE_DMA = 0xCA,
    ATAPI_WRITE_DMA_QUEUED = 0xCC,
    ATAPI_WRITE_MULTIPLE = 0xC5,
    ATAPI_WRITE_SECTORS = 0x30,

    ATAPI_READ_DMA = 0xC8,
    ATAPI_READ_DMA_QUEUED = 0xC7,
    ATAPI_READ_MULTIPLE = 0xC4,
    ATAPI_READ_SECTORS = 0x20,

    ATAPI_WRITE_DMA_EXT = 0x35,
    ATAPI_WRITE_DMA_QUEUED_EXT = 0x36,
    ATAPI_WRITE_MULTIPLE_EXT = 0x39,
    ATAPI_WRITE_SECTORS_EXT = 0x34,

    ATAPI_READ_DMA_EXT = 0x25,
    ATAPI_READ_DMA_QUEUEDEXT = 0x26,
    ATAPI_READ_MULTIPLE_EXT = 0x29,
    ATAPI_READ_SECTORS_EXT = 0x24,

    ATAPI_PACKET = 0xA0,
    ATAPI_DEVICE_RESET = 0x08,

    ATAPI_SERVICE = 0xA2,
    ATAPI_NOP = 0,
    ATAPI_NOP_NOP_AUTOPOLL = 1,

    ATAPI_GET_MEDIA_STATUS = 0xDA,

    ATAPI_FLUSH_CACHE = 0xE7,
    ATAPI_FLUSH_CACHE_EXT = 0xEA,

    ATAPI_DATA_SET_MANAGEMENT = 0x06,
    ATAPI_MEDIA_EJECT = 0xED,

    ATAPI_IDENTIFY_PACKET_DEVICE = 0xA1,
    ATAPI_IDENTIFY_DEVICE = 0xEC,

    ATAPI_SET_FEATURES = 0xEF,

    ATAPI_SET_FEATURES_ENABLE_RELEASE_INT = 0x5D,
    ATAPI_SET_FEATURES_ENABLE_SERVICE_INT = 0x5E,

    ATAPI_SET_FEATURES_DISABLE_RELEASE_INT = 0xDD,
    ATAPI_SET_FEATURES_DISABLE_SERVICE_INT = 0xDE
};