/*
 * kernel/arch/aarch64/asm/midr.h
 * © suhas pai
 */

#pragma once

enum midr_arch {
    MIDR_ARCH_ARMV4 = 1,
    MIDR_ARCH_ARMV4T,
    MIDR_ARCH_ARMV5_OBSOLETE,
    MIDR_ARCH_ARMV5T,
    MIDR_ARCH_ARMV5TE,
    MIDR_ARCH_ARMV5TEJ,
    MIDR_ARCH_ARMV6,
};

enum midr_implementer {
    MIDR_IMPLEMENTER_ARM = 0x41,
    MIDR_IMPLEMENTER_BROADCOM,
    MIDR_IMPLEMENTER_CAVIUM,
    // DEE = Digital Equipment Corporation.
    MIDR_IMPLEMENTER_DEE,
    MIDR_IMPLEMENTER_FUJITSU = 0x46,
    MIDR_IMPLEMENTER_INFINEON = 0x49,
    MIDR_IMPLEMENTER_MOTOROLA = 0x4D,
    MIDR_IMPLEMENTER_NVIDIA,
    MIDR_IMPLEMENTER_AMC = 0x50,
    MIDR_IMPLEMENTER_QUALCOMM,
    MIDR_IMPLEMENTER_MARVELL = 0x56,
    MIDR_IMPLEMENTER_INTEL = 0x69,
    MIDR_IMPLEMENTER_AMPERE = 0xC0,
};

enum midr_shifts {
    MIDR_REVISION_SHIFT = 0,
    MIDR_PARTNUM_SHIFT = 4,
    MIDR_VARIANT_SHIFT = 20,
    MIDR_IMPLEMENTER_SHIFT = 24
};

enum midr_flags {
    __MIDR_REVISION = 0b1111ull << MIDR_REVISION_SHIFT,
    __MIDR_PARTNUM = 0xfffull << MIDR_PARTNUM_SHIFT,
    __MIDR_VARIANT = 0b1111ull << MIDR_VARIANT_SHIFT,
    __MIDR_IMPLEMENTER = 0xffull << MIDR_IMPLEMENTER_SHIFT
};