/*
 * kernel/arch/x86_64/asm/exceptions.h
 * © suhas pai
 */

#pragma once

enum exception {
    EXCEPTION_DIVIDE_BY_ZERO,
    EXCEPTION_DEBUG,

    // NMI = Non-Maskable Interrupt
    EXCEPTION_NMI,

    // Breakpoint = Debug Trap
    EXCEPTION_BREAKPOINT,

    // Overflow = Arithmetic Overflow
    EXCEPTION_OVERFLOW,

    // Bound = Array Bounds Exceeded. For BOUND instruction
    EXCEPTION_BOUND,

    EXCEPTION_INVALID_OPCODE,
    EXCEPTION_DEVICE_NOT_AVAILABLE,
    EXCEPTION_DOUBLE_FAULT,

    EXCEPTION_COPROCESSOR_SEGMENT_OVERRUN,
    EXCEPTION_INVALID_TSS,

    EXCEPTION_SEGMENT_NOT_PRESENT,
    EXCEPTION_STACK_FAULT,
    EXCEPTION_GENERAL_PROTECTION_FAULT,
    EXCEPTION_PAGE_FAULT,

    // 15 = Reserved

    EXCEPTION_FPU_FAULT = 16,
    EXCEPTION_ALIGNMENT_CHECK,
    EXCEPTION_MACHINE_CHECK,
    EXCEPTION_SIMD_FLOATING_POINT,
    EXCEPTION_VIRTUALIZATION_EXCEPTION,
    EXCEPTION_CONTROL_PROTECTION_EXCEPTION,

    // 22-27 = Reserved
    EXCEPTION_HYPERVISOR_EXCEPTION = 28,
    EXCEPTION_VMM_EXCEPTION,
    EXCEPTION_SECURITY_EXCEPTION,
};